# Generated by Django 5.2.16 on 2026-07-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tag keywords'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='task',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Task/Domain category (e.g. customer-support)', max_length=100),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='name',
            field=models.CharField(help_text='Human-readable name for the prompt', max_length=255, unique=True),
        ),
    ]
